@echo off
REM Financial Regulatory Copilot Chile - GitHub Setup Script
REM =======================================================

chcp 65001 >nul
echo.
echo ============================================
echo   Financial Regulatory Copilot Chile
 echo   Setup para GitHub
 echo ============================================
echo.

REM Verificar si git esta instalado
git --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ ERROR: Git no esta instalado
    echo    Por favor instala Git primero: https://git-scm.com/downloads
    pause
    exit /b 1
)

echo ✅ Git esta instalado: %git --version%
echo.

REM Verificar si estas en el directorio correcto
if not exist "app\main.py" (
    echo ❌ ERROR: No estas en el directorio del proyecto
    echo    Ve a: C:\Users\angel\OneDrive\Escritorio\llamaindex
    pause
    exit /b 1
)

echo ✅ Directorio del proyecto verificado
echo.

REM Inicializar repositorio Git
echo Inicializando repositorio Git...
git init
echo.

REM Anadir todos los archivos (excepto __pycache__ y .gitignore)
echo Anadiendo archivos a Git...
git add .
echo.

REM Hacer primer commit
echo Haciendo primer commit...
git commit -m "Initial commit: Financial Regulatory Copilot Chile v0.1.0

- Added complete Streamlit application structure
- Core agent components (FinancialAgent, KnowledgeBase, DataRecommender)
- Streamlit components (FileUploader, ChatInterface, RecommendationEngine)
- Session manager and utilities
- Requirements and documentation

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"

echo.
echo ✅ Repositorio local creado
 echo.
echo ============================================
echo   SIGUIENTES PASOS:
 echo ============================================
echo.
echo 1. Crea un nuevo repositorio en GitHub:
 echo    https://github.com/new
 echo.
echo 2. Nombre sugerido: financial-regulatory-copilot-chile
 echo.
echo 3. Ejecuta estos comandos:
 echo.
echo   git remote add origin https://github.com/TU_USUARIO/financial-regulatory-copilot-chile.git
 echo   git branch -M main
 echo   git push -u origin main
 echo.
echo 4. Si te pide autenticacion, sigue las instrucciones de GitHub
 echo.
echo ============================================
echo.
pause
